# Basic Numpy
- Numpy is a python Numerical Python Package
- It is Used in ML,CV,NLP,Tensorflow
- Python Array Packages

In [2]:
import numpy as np

### Create an Array Using Numpy

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)
##nd means ndimensional

numpy.ndarray

In [28]:
## we can create Hetrogenous Datatype
arr = np.array([1,2,3,4,"Karthik",55.5,4+8j])
arr

array(['1', '2', '3', '4', 'Karthik', '55.5', '(4+8j)'], dtype='<U64')

In [29]:
arr.ndim
## It is One Dimensional Array

1

In [7]:
for i in arr:
    print(f'Data type is : {type(i)} and the Value is :{i}')
## Now we see when we use string all element are changes into str

Data type is : <class 'numpy.str_'> and the Value is :1
Data type is : <class 'numpy.str_'> and the Value is :2
Data type is : <class 'numpy.str_'> and the Value is :3
Data type is : <class 'numpy.str_'> and the Value is :4
Data type is : <class 'numpy.str_'> and the Value is :Karthik
Data type is : <class 'numpy.str_'> and the Value is :55.5
Data type is : <class 'numpy.str_'> and the Value is :(4+8j)


In [8]:
## Same like Float 
arr = np.array([1,2,23,4,5.0,4])
print(f"Orginal Array is {arr}")
for i in arr:
    print(f'Data type is : {type(i)} and the Value is :{i}')


Orginal Array is [ 1.  2. 23.  4.  5.  4.]
Data type is : <class 'numpy.float64'> and the Value is :1.0
Data type is : <class 'numpy.float64'> and the Value is :2.0
Data type is : <class 'numpy.float64'> and the Value is :23.0
Data type is : <class 'numpy.float64'> and the Value is :4.0
Data type is : <class 'numpy.float64'> and the Value is :5.0
Data type is : <class 'numpy.float64'> and the Value is :4.0


## Create 2dimensional(2d) & 3d Array

In [12]:
arr = np.array([[1,2,3],["Python","Django","Javascript"]])
print(arr)

[['1' '2' '3']
 ['Python' 'Django' 'Javascript']]


In [13]:
arr.ndim ## 2d array
## Now we see it has 2rows and 3 columns so it is 2d Array

2

In [14]:
arr = np.array([[[1,2,3],["Python","Django","Javascript"],["Karthik","Saran","S"]]])
print(arr)
arr.ndim ##3d array
## Now we see It is 3d(dimensional) Array       

[[['1' '2' '3']
  ['Python' 'Django' 'Javascript']
  ['Karthik' 'Saran' 'S']]]


3

## Now we create ndimension using another method using ndim

In [15]:
arr = np.array([1,2,4,5] , ndmin=3)
print(arr)
arr.ndim
## Now we create a 3dimension

[[[1 2 4 5]]]


3

In [32]:
np.array([1,2,4,5] , dtype=complex) ## Now we convert into Complex using dtype

array([1.+0.j, 2.+0.j, 4.+0.j, 5.+0.j])

In [16]:
arr = np.array([(10,20),(100,200)])
print(arr)
arr.ndim
## We create using Tuple 

[[ 10  20]
 [100 200]]


2

In [42]:
arr = np.array([[10,20],[100,200]])
print(arr)
arr.shape

[[ 10  20]
 [100 200]]


(2, 2)

In [45]:
arr[0],arr[0][1]

(array([10, 20]), 20)

## Change Int16 & Int64
- It is Not Widely Used in Datascience

In [67]:
arr = np.array([(1,2),(3,4)] , dtype=[("a","<i2"),("b","<i8")] )
print(arr)
arr.shape

[(1, 2) (3, 4)]


(2,)

## a i= 1, b = 2 likewise a =3 and b=4
- i2 =16bit
- i4 =32bit
- i8 =64bit

In [68]:
## Now we see  Int16
print(arr[0][0])
type(arr[0][0])

1


numpy.int16

In [69]:
## Now we see  Int64
print(arr[0][1])
type(arr[0][1])

2


numpy.int64

## Access Element in Array 

In [7]:
arr = np.array([[10,20],[100,200],[1000,3000]])
arr

array([[  10,   20],
       [ 100,  200],
       [1000, 3000]])

In [78]:
arr[0] , arr[1] , arr[0][1] , arr[2][1]

(array([10, 20]), array([100, 200]), 20, 3000)

In [81]:
print(arr[1][1])
type(arr[1][1]) ## By default int has 32

200


numpy.int32

## Matrix
- Matrix & Array are Almost Similar

In [11]:
matrix = np.mat(arr)
matrix
## Now we see it Changes Array  into Matrix 

matrix([[  10,   20],
        [ 100,  200],
        [1000, 3000]])

In [11]:
type(matrix)

numpy.matrix

In [20]:
matrix[1]

matrix([[100, 200]])

## convert List Into Array

In [23]:
## Now we create a list & Convert into Array
lst =[i for i in range(1,6)]
lst , type(lst)

([1, 2, 3, 4, 5], list)

In [28]:
## Convert list into Array
np.array(lst,ndmin=2)

array([[1, 2, 3, 4, 5]])

In [32]:
## Another Wayy  (AnyArray)
print(np.asanyarray(lst))
## It will not convert into array now we see with matrix 
np.asanyarray(matrix)

[1 2 3 4 5]


matrix([[  10,   20],
        [ 100,  200],
        [1000, 3000]])

In [33]:
## another Method (asarray)
print(np.asarray(lst))
## It will  convert into array now we see with matrix 
np.asarray(matrix)

[1 2 3 4 5]


array([[  10,   20],
       [ 100,  200],
       [1000, 3000]])

## Subclass

In [44]:
## Now wee see Matrix is a subclass of an array 
## Know we see with subclass function
print(f"Matrix is a Subclass of Array : {issubclass(np.matrix , np.ndarray)}")
print(f"Array is a Subclass of Matrix : {issubclass(np.ndarray , np.matrix)}")

Matrix is a Subclass of Array : True
Array is a Subclass of Matrix : False


## Deep  Copy Vs Shallow Copy

In [87]:
arr

array([[  10,   20],
       [ 100,  200],
       [1000, 3000]])

In [46]:
## Shallow Copy
a = arr
a

array([[  10,   20],
       [ 100,  200],
       [1000, 3000]])

In [48]:
## Deep Copy
b = np.copy(arr)
b 

array([[  10,   20],
       [ 100,  200],
       [1000, 3000]])

In [88]:
## To update a value in  arr 
arr[0][0] = 50
arr

array([[  50,   20],
       [ 100,  200],
       [1000, 3000]])

In [50]:
a 
## Now we see it Update the New Value , it refects the new changes becozz it gives shares same  location of arr

array([[  50,   20],
       [ 100,  200],
       [1000, 3000]])

In [51]:
b 
## Now we see It doesn't update the New value , it cant reflect the new changes becozz it gives doesn't shares same  location of arr

array([[  10,   20],
       [ 100,  200],
       [1000, 3000]])

## Array Are Mutuable and Supports Slicing

In [89]:
arr

array([[  50,   20],
       [ 100,  200],
       [1000, 3000]])

In [90]:
arr[0][0]=10
arr ## Mutuable

array([[  10,   20],
       [ 100,  200],
       [1000, 3000]])

In [94]:
## Slicing 
arr[-1] 

array([1000, 3000])

In [95]:
arr[1,:]## First One is for Which Row

array([100, 200])

In [103]:
print(arr[2:])
arr[2:][0][0]

[[1000 3000]]


1000

In [105]:
for i in arr:
    print(i)

[10 20]
[100 200]
[1000 3000]


In [107]:
np.array([10,20]) + np.array([30,40])

array([40, 60])

In [112]:
list([10,20]) + list([30,40])

[10, 20, 30, 40]

In [113]:
np.fromfunction(lambda i , j:i==j,(2,3))
## Becozz it create  2  row and 3 column ,here 1 = 0row and 0 column so true , 2=0row and 1column so false ,3 row 2 and column so false
## 4=row 0 column false , 5 =1row 1 column so true   ,6 =1row and 2column so false 
## result is(t,f,f,f,t,f)

array([[ True, False, False],
       [False,  True, False]])

In [117]:
np.fromfunction(lambda i,j:i+j,(2,3))

array([[0., 1., 2.],
       [1., 2., 3.]])

In [116]:
np.fromfunction(lambda i,j:i/j,(2,3))
## In Numpy We dont get zero division error instead it gives inf

C:\ProgramData\Anaconda3\envs\pandas\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\envs\pandas\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5]])

## Generator

In [4]:
def fib(n):
    a,b=0,1
    if(n<0):
        yield("Sorry Not Possible")
    elif(n==1):
        print("The Fibonacii series are")
        yield(a)
    else:
        for i in range(n):
            yield(a)
            a,b=b,a+b
            if(a>n):
                break
for i in fib(5):
    print(i)
        

0
1
1
2
3


## creating Array With Various Datatypes using from function

In [154]:
## Numpy Iterator
np.fromiter(fib(5),dtype = int)

array([0, 1, 1, 2, 3])

In [155]:
def test(n):
    for i in range(n):
        yield i
np.fromiter(test(5),dtype=int)

array([0, 1, 2, 3, 4])

In [157]:
## Create an array using Range
np.fromiter(range(5),dtype =int)

array([0, 1, 2, 3, 4])

In [5]:
## Create an Array Using String
np.fromstring('1,2,3,4,5',sep=',',dtype=int)

array([1, 2, 3, 4, 5])

## Check Dimension of the Array we use ndim

In [18]:
## Convert nested list into array 
lst1 = [[1,2,3,4],[10,20,30,40],[100,200,300,400]]
lst1

[[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]]

In [19]:
arr1 = np.array(lst1)
print(arr1)
arr1.ndim

[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]


2

## check Size & shape

In [22]:
## tells how many elements are available in the array
arr1.size

12

In [24]:
## gives rows and columns  
arr1.shape ## 3 rows 4 columns

(3, 4)

In [47]:
## Check datatype using dtype
arr1.dtype                        

dtype('int32')

## 3d Array

In [53]:
## 3dimensional array
arr2 = np.array([[[10,20,30,40],[1,2,3,4]],[[1000,2000,3000,4000],[40,30,20,10]]])
print(arr2)
print(arr2.size)
print(arr2.ndim)

[[[  10   20   30   40]
  [   1    2    3    4]]

 [[1000 2000 3000 4000]
  [  40   30   20   10]]]
16
3


In [43]:
arr2.shape
# this means 2 times 2 X 4(2row,4column)

(2, 2, 4)

In [56]:
print(np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3).shape)
np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)

(1, 3, 3)


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [63]:
b = [   [[1,2],[3,4]] , [[5,6],[7,8]] , [[100,200],[1000,2000]]   ]
print(np.array(b).shape)
print(np.array(b).ndim)
np.array(b)

(3, 2, 2)
3


array([[[   1,    2],
        [   3,    4]],

       [[   5,    6],
        [   7,    8]],

       [[ 100,  200],
        [1000, 2000]]])

In [65]:
c =  [   [[1,2,3,4]] , [[5,6,7,8]] , [[100,200,1000,2000]]   ]
print(np.array(c))
np.array(c).shape

[[[   1    2    3    4]]

 [[   5    6    7    8]]

 [[ 100  200 1000 2000]]]


(3, 1, 4)

## 4d array
- It is Impossible to view 4d array

In [58]:
arr4 = np.array([[[[10,20,30,40],[100,200,300,400],[1000,2000,3000,4000],[10000,20000,30000,4000]]]])
print(arr4)
print(arr4.size)
print(arr4.ndim)

[[[[   10    20    30    40]
   [  100   200   300   400]
   [ 1000  2000  3000  4000]
   [10000 20000 30000  4000]]]]
16
4


In [59]:
arr4.shape
# this means

(1, 1, 4, 4)

## Arrange
- Similar to range function but it supports arange

In [2]:
print(list(range(6)))
list(range(6.5))

[0, 1, 2, 3, 4, 5]


TypeError: 'float' object cannot be interpreted as an integer

In [14]:
## But in arange it support float
np.arange(6.5,9,.3)

array([6.5, 6.8, 7.1, 7.4, 7.7, 8. , 8.3, 8.6, 8.9])

## Creating Dummy Array

In [2]:
## linespace it gives a value between number bedefault it gives 50
print(f'Size : {np.linspace(1,2,100).size}')
np.linspace(1,2,100)

Size : 100


array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [21]:
print(np.linspace(2,4,4)) ## it include 4 
np.linspace(2,4,4,endpoint=False) ## it doesn't include 4

[2.         2.66666667 3.33333333 4.        ]


array([2. , 2.5, 3. , 3.5])

In [4]:
## Creating Array with zeros 
print(np.zeros(5))
np.zeros((2,5))  ## 2 row 5 column 

[0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
## Creating Array with ones
print(np.zeros(5))
np.zeros((3,5))  ## 2 row 5 column 

[0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((2,3,5))+6

array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]])

In [16]:
## empty array 
np.empty((3,4))  ## Gives some random data

array([[1.18691046e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.04082753e-047, 7.79294625e-091,
        5.05574677e-038],
       [2.81117593e-033, 1.29233700e+161, 3.99910963e+252,
        1.23971686e+224]])

In [18]:
## Gives Diagnol Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
## Gives Log Data 
print(np.logspace(1,5,4)) ## So Between 1,5 it Gerates 4 logdata which base is 10
print(np.logspace([1,2],5))
print(f'Dimension : {np.logspace([1,3],5).ndim}')
print(np.logspace([1,3],5).shape)

[1.00000000e+01 2.15443469e+02 4.64158883e+03 1.00000000e+05]
[[1.00000000e+01 1.00000000e+02]
 [1.20679264e+01 1.15139540e+02]
 [1.45634848e+01 1.32571137e+02]
 [1.75751062e+01 1.52641797e+02]
 [2.12095089e+01 1.75751062e+02]
 [2.55954792e+01 2.02358965e+02]
 [3.08884360e+01 2.32995181e+02]
 [3.72759372e+01 2.68269580e+02]
 [4.49843267e+01 3.08884360e+02]
 [5.42867544e+01 3.55648031e+02]
 [6.55128557e+01 4.09491506e+02]
 [7.90604321e+01 4.71486636e+02]
 [9.54095476e+01 5.42867544e+02]
 [1.15139540e+02 6.25055193e+02]
 [1.38949549e+02 7.19685673e+02]
 [1.67683294e+02 8.28642773e+02]
 [2.02358965e+02 9.54095476e+02]
 [2.44205309e+02 1.09854114e+03]
 [2.94705170e+02 1.26485522e+03]
 [3.55648031e+02 1.45634848e+03]
 [4.29193426e+02 1.67683294e+03]
 [5.17947468e+02 1.93069773e+03]
 [6.25055193e+02 2.22299648e+03]
 [7.54312006e+02 2.55954792e+03]
 [9.10298178e+02 2.94705170e+03]
 [1.09854114e+03 3.39322177e+03]
 [1.32571137e+03 3.90693994e+03]
 [1.59985872e+03 4.49843267e+03]
 [1.93069773e+

In [20]:
np.logspace(2,5,4)

array([   100.,   1000.,  10000., 100000.])

## Reshpae an array

In [2]:
d = np.linspace(1,10,20)
print(d.ndim)
print(d.shape)
d # it has 1 row 20 columns 

1
(20,)


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [41]:
## reshape 
## now we change into 20 rows and 1 column
print(d.reshape(20,1).shape)
d.reshape(20,1)

(20, 1)


array([[ 1.        ],
       [ 1.47368421],
       [ 1.94736842],
       [ 2.42105263],
       [ 2.89473684],
       [ 3.36842105],
       [ 3.84210526],
       [ 4.31578947],
       [ 4.78947368],
       [ 5.26315789],
       [ 5.73684211],
       [ 6.21052632],
       [ 6.68421053],
       [ 7.15789474],
       [ 7.63157895],
       [ 8.10526316],
       [ 8.57894737],
       [ 9.05263158],
       [ 9.52631579],
       [10.        ]])

In [48]:
d.reshape(1,2,10) # 1 times 2row 10columns

array([[[ 1.        ,  1.47368421,  1.94736842,  2.42105263,
          2.89473684,  3.36842105,  3.84210526,  4.31578947,
          4.78947368,  5.26315789],
        [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,
          7.63157895,  8.10526316,  8.57894737,  9.05263158,
          9.52631579, 10.        ]]])

In [54]:
np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3).shape

(1, 3, 3)

In [75]:
## To Create a random data 
print(np.random.rand(3)) ## it gives data in uniform way 0 to 1
print(np.random.randn(3)) ## it gives data by standard normal distribution -1 to 1
print(np.random.randn(2,2,3))
print(np.random.randint(5,50,(4,4))) ## It gives 4x4 array between 5 to 50

[0.51785266 0.01807238 0.77346229]
[0.46270746 0.91230893 1.82145203]
[[[-0.67000351 -1.06136945 -0.61884324]
  [-2.78098946  0.59192479  1.29408052]]

 [[-0.87468256 -0.25462006 -0.12182228]
  [-0.4188338   0.33207195 -0.27154289]]]
[[ 9  7 16 42]
 [34 27  7 40]
 [49 46 18 18]
 [ 8 30 31 38]]


In [85]:
a = np.random.randint(1,10,(5,5))
print(a.min()) ; print(a.mean()) ## minimum  and mean
print(a.max())## Maximum
a

1
5.28
9


array([[1, 4, 4, 9, 3],
       [7, 8, 7, 5, 9],
       [2, 9, 3, 3, 1],
       [5, 4, 5, 1, 6],
       [9, 8, 2, 9, 8]])

## Indexing & Slicing

In [5]:
arr = np.random.randint(4,100,(5,5))
arr

array([[ 5,  7, 23, 38, 72],
       [67, 58, 87, 73, 75],
       [ 7, 21, 50, 45, 89],
       [72, 30, 52, 33, 67],
       [39, 81, 17, 33, 49]])

In [6]:
arr[3:,3:] ## start from 3 row and start from 3rd column

array([[33, 67],
       [33, 49]])

In [7]:
arr[:,[1,3]] ## all rows only 1st and 3rd column

array([[ 7, 38],
       [58, 73],
       [21, 45],
       [30, 33],
       [81, 33]])

In [8]:
print(arr >10) ## anything greater than 10 gives True
arr[arr>10] ## it gives only filter arrray

[[False False  True  True  True]
 [ True  True  True  True  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


array([23, 38, 72, 67, 58, 87, 73, 75, 21, 50, 45, 89, 72, 30, 52, 33, 67,
       39, 81, 17, 33, 49])

In [9]:
## Normal Multiplication 
print(arr)
arr*arr ## Multiply by arr*arr ex : 5*5=25 ; 67*67 = 4489

[[ 5  7 23 38 72]
 [67 58 87 73 75]
 [ 7 21 50 45 89]
 [72 30 52 33 67]
 [39 81 17 33 49]]


array([[  25,   49,  529, 1444, 5184],
       [4489, 3364, 7569, 5329, 5625],
       [  49,  441, 2500, 2025, 7921],
       [5184,  900, 2704, 1089, 4489],
       [1521, 6561,  289, 1089, 2401]])

## Matrix Multiplication

In [10]:
 ## if we want Matrix Multiplication  we use @
print(arr)
arr@arr   ## [5*5 +  7*67 + 23*7 + 38*72 + 72*39] ==> 6199 ; [5*7 + 7*58 + 23*21 +38*30 + 72*81] ==> 7896
## Import Rule in Matrix Multiplication is Your 1st Matrix column and 2 nd Matrix row is always same  

[[ 5  7 23 38 72]
 [67 58 87 73 75]
 [ 7 21 50 45 89]
 [72 30 52 33 67]
 [39 81 17 33 49]]


array([[ 6199,  7896,  5074,  5366,  9006],
       [13011, 13925, 16008, 15579, 25483],
       [ 8503, 10876,  8341,  8471, 13905],
       [ 7723,  9753,  9721, 10566, 17556],
       [10028, 10287, 11343, 10866, 15008]])

In [15]:
print(25+469+161+2736+2808)
print(35+406+483+1140+5832)

6199
7896


In [26]:
mat1 = np.random.rand(2,3) ## 2 row 3 column 
mat2 = np.random.rand(2,3)  ## 2 row 3 coumn 
print(mat1); print(mat2)
## criteria not match for  matrix multiplication so it gives error 
mat1@mat2

[[0.2680563  0.69056088 0.54936369]
 [0.86088046 0.67233135 0.75129993]]
[[0.12552153 0.76717596 0.03704994]
 [0.52387722 0.72761433 0.88330303]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [30]:
## But index multiplication is Available 
mat1 * mat2

array([[0.03364684, 0.5297817 , 0.02035389],
       [0.45099566, 0.48919792, 0.6636255 ]])

In [31]:
mat1 / 0 ## It always gives infinity

C:\ProgramData\Anaconda3\envs\pandas\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf]])

## BroadCasting

In [41]:
zer = np.zeros((3,4))
a = np.array((1,2,3,4))
print(zer) ;print(); print(a) ; print()
print(zer+a)  ## This is Broadscasting

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[1 2 3 4]

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [44]:
b = np.array((1,2,3)) 
print(b)
print(b.shape)
zer+b  ## Shape is not correct

[1 2 3]
(3,)


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [49]:
## we can reshape 
c = b.reshape(3,1)
print(c)
print(zer)
c+ zer

[[1]
 [2]
 [3]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [55]:
## Transpose the Array 
t = np.array([[1,2,3]])
print(t) ; print()
print(t.T) ## Transpose 1 x 3 ==>  3 x 1

[[1 2 3]]

[[1]
 [2]
 [3]]


In [63]:
## find the sqrt 
sq = np.random.rand(5,4)
print(sq) ; print()
print(sq.T) ; print()
print("The Orginal Array is")
print(sq)
sqrt = np.sqrt(sq)
sqrt

[[0.5239932  0.41118463 0.95981036 0.62522064]
 [0.43480253 0.72051514 0.38141366 0.57043335]
 [0.49247862 0.71464999 0.01219413 0.49184199]
 [0.82892943 0.66004264 0.48725363 0.63588971]
 [0.26115638 0.51519592 0.59475407 0.94966313]]

[[0.5239932  0.43480253 0.49247862 0.82892943 0.26115638]
 [0.41118463 0.72051514 0.71464999 0.66004264 0.51519592]
 [0.95981036 0.38141366 0.01219413 0.48725363 0.59475407]
 [0.62522064 0.57043335 0.49184199 0.63588971 0.94966313]]

The Orginal Array is
[[0.5239932  0.41118463 0.95981036 0.62522064]
 [0.43480253 0.72051514 0.38141366 0.57043335]
 [0.49247862 0.71464999 0.01219413 0.49184199]
 [0.82892943 0.66004264 0.48725363 0.63588971]
 [0.26115638 0.51519592 0.59475407 0.94966313]]


array([[0.72387374, 0.64123679, 0.97969912, 0.79070894],
       [0.65939558, 0.84883163, 0.61758696, 0.75527038],
       [0.70176821, 0.84536974, 0.11042702, 0.70131447],
       [0.91045562, 0.81243008, 0.69803555, 0.79742693],
       [0.51103461, 0.71777149, 0.771203  , 0.97450661]])

In [72]:
0.5239932** 0.5

0.7238737458977221

In [73]:
## Exponential 
np.exp(sq)

array([[1.68875775, 1.50860386, 2.61120124, 1.8686582 ],
       [1.544658  , 2.0554918 , 1.46435322, 1.7690335 ],
       [1.63636713, 2.04347133, 1.01226878, 1.63532569],
       [2.29086489, 1.93487483, 1.62783943, 1.88870179],
       [1.29843069, 1.67396643, 1.81258511, 2.58483877]])

In [76]:
## log base10
np.log10(sq)

array([[-0.28067435, -0.38596313, -0.01781457, -0.2039667 ],
       [-0.36170794, -0.14235689, -0.41860376, -0.24379509],
       [-0.30761262, -0.14590661, -1.91384927, -0.3081744 ],
       [-0.08148244, -0.18042801, -0.31224491, -0.1966182 ],
       [-0.58309936, -0.28802759, -0.22566258, -0.02243042]])

## ranom seed
- It helps to not change the random value

In [81]:
for i in range(5):
    print(np.random.rand(2,4))
    print() 
## Now we see values are changing 

[[0.46215307 0.8356833  0.43378372 0.82626956]
 [0.61819191 0.44545826 0.71123213 0.26270917]]

[[0.30821113 0.56522702 0.82622056 0.66455673]
 [0.41046834 0.60115692 0.58694049 0.97261458]]

[[0.16806063 0.23388022 0.44624837 0.31691301]
 [0.85157663 0.64064027 0.87752236 0.02539357]]

[[0.17536579 0.62062281 0.55458086 0.46641094]
 [0.37067522 0.87389359 0.91844928 0.17996195]]

[[0.9408076  0.38405494 0.48817018 0.37828906]
 [0.95290355 0.68736899 0.57617692 0.63558919]]



In [89]:
for i in range(5):
    np.random.seed(5) ## we can give any number we want, if we give 5 anytime we get same value 
    print(np.random.rand(2,4))
    print()
## Now we see values not are changing 

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]



In [90]:
for i in range(5):
    np.random.seed(5) ## we can give any number we want, if we give 50 anytime we get same value 
    print(np.random.rand(2,4))
    print()
## Now we see values not are changing 

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]



In [93]:
for i in range(5):
    np.random.seed(5) ## we can give any number we want, if we give 5 anytime we get same value 
    print(np.random.rand(2,4))
    print()
## Now we see values not are changing 

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]]



## change the Dimension of the Array

In [3]:
s = np.array([[
    [100,60],
    [200,70]
]])
s

array([[[100,  60],
        [200,  70]]])

In [4]:
s.shape ## 1 dimension array

(1, 2, 2)

In [5]:
s.ndim

3

In [6]:
## 2 dimension array
s.shape = (2,2,1)

In [7]:
s

array([[[100],
        [ 60]],

       [[200],
        [ 70]]])

In [8]:
s.shape

(2, 2, 1)

In [11]:
s.ndim 

3